name: ImpostorManhunt
version: '1.0'
main: shray.us.impostormanhunt.Main
api-version: '1.21'
description: Impostor Manhunt
commands:
  announce:
    description: "Announces your location"
    usage: /announce
  lost:
    description: "Asks for help"
    usage: /lost
  track:
    description: "Chooses what to track with the compass"
    usage: /track (closest|<username>|portal)
  goto:
    description: "Makes you go to a player"
    usage: /goto <username>
  ImpostorManhunt:
    description: "ImpostorManhunt commands"
    usage: /ImpostorManhunt <args>
depend: [ProtocolLib]